name: SYCL hardening check

permissions: read-all

on:
  workflow_call:
    inputs:
      linux_toolchain_artifact:
        type: string
        default: sycl_linux_default
      linux_toolchain_artifact_filename:
        type: string
        default: sycl_linux.tar.gz
      linux_toolchain_decompress_command:
        type: string
        default: gunzip

      windows_toolchain_artifact:
        type: string
        default:
      windows_toolchain_artifact_filename:
        type: string
  
  workflow_dispatch:
    inputs:
      linux_toolchain_artifact:
        type: string
        default: sycl_linux_default
      linux_toolchain_artifact_filename:
        type: string
        default: sycl_linux.tar.gz
      linux_toolchain_decompress_command:
        type: string
        default: gunzip

      windows_toolchain_artifact:
        type: string
        default: sycl_windows_default
      windows_toolchain_artifact_filename:
        type: string
        default: sycl_windows.tar.gz

jobs:
  hardening_check:
    runs-on: ubuntu-latest

    steps:
    - name: Install hardening-check
      run: |
        sudo apt update
        sudo apt install -y devscripts

    - name: Download SYCL toolchain
      run: wget https://github.com/intel/llvm/releases/download/nightly-2026-02-03/sycl_linux.tar.gz
    #   uses: actions/download-artifact@v7
    #   with:
    #     name: ${{ inputs.linux_toolchain_artifact }}

    - name: Extract SYCL toolchain
      run: |
        mkdir toolchain
        tar -I '${{ inputs.linux_toolchain_decompress_command }}' -xf ${{ inputs.linux_toolchain_artifact_filename }} -C toolchain

    - name: Perform checks
      run: |
        for file in ./toolchain/bin/*; do
            hardening-check "$file" | tee -a "./hardening-check.txt"
        done

        for file in $(find ./toolchain/lib/ -type f -name "*.so*"); do
            hardening-check "$file" | tee -a "./hardening-check.txt"
        done

    - uses: actions/upload-artifact@v6
      with:
        name: hardening-check
        path: hardening-check.txt

  winchecksec:
    runs-on: windows-latest

    steps:
    - name: Install winchecksec
      run: |
        curl -LO https://github.com/trailofbits/winchecksec/releases/download/v3.1.0/windows.x64.Release.zip
        mkdir winchecksec
        unzip "windows.x64.Release.zip" -d winchecksec

    - name: Download SYCL toolchain
      shell: bash
      run: wget https://github.com/intel/llvm/releases/download/nightly-2026-02-03/sycl_windows.tar.gz
      # uses: actions/download-artifact@v7
      # with:
      #   name: ${{ inputs.windows_toolchain_artifact }}

    - name: Extract SYCL toolchain
      shell: bash
      run: |
        mkdir toolchain
        tar -xf ${{ inputs.windows_toolchain_artifact_filename }} -C toolchain

    - name: Perform checks
      shell: bash
      run: |
        for file in $(find ./toolchain/bin/ -type f -name "*.exe"); do
            ./winchecksec/build/Release/winchecksec.exe "$file" | tee -a "./winchecksec.txt"
        done

        for file in $(find ./toolchain/bin/ -type f -name "*.dll"); do
            ./winchecksec/build/Release/winchecksec.exe "$file" | tee -a "./winchecksec.txt"
        done

    - uses: actions/upload-artifact@v6
      with:
        name: winchecksec
        path: winchecksec.txt
