# The actual version of this file can be found on the latest sycl-rel-* branch.
# A new release branch copies this file from the latest release branch.
# This file is still needed to launch the workflow on another branches.

name: SYCL Release Branch Nightly

on:
  workflow_dispatch:

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Doing nothing"
          touch sycl_linux.tar.gz sycl_windows.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sycl_linux_release
          path: sycl_linux.tar.gz
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sycl_windows_release
          path: sycl_windows.tar.gz
  sign-release-builds:
    needs: dummy
    name: Trigger sign-release-builds workflow
    uses: ./.github/workflows/sycl-sign-release-builds.yml
