# This workflow performs trivy check of docker config files.
# It triggers only on pushs to devops/containers.
# For more info: https://github.com/aquasecurity/trivy-action

name: Trivy

on:
  pull_request:
    paths:
      - 'devops/containers/**'
  workflow_dispatch:

jobs:
  build:
    name: Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: devops

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: 'config'
          scan-ref: devops/containers
          trivyignores: devops/.trivyignore.txt
          exit-code: 1
