name: WindowsByComment

on:
  issue_comment:
    types: [created]

permissions:
  contents: read

jobs:
  windows_default:
    name: Windows
    if: github.repository == 'intel/llvm'
    uses: ./.github/workflows/sycl_windows_build_and_test.yml
